theme: jekyll-theme-minimal
title: Gäbistrasse 3 
description: Wir vermieten unsere Ferienwohnung im Lötschental an Freunde und Familie. Perfekt für Schneesportbegeisterte, Wandervögel und Plöischler.  
logo: logo.jpg
